version: '3'
services:

## Applications Code Container #############################
  mariadb:
    build:
      context: ./containers/mariadb
    volumes:
        - mysql:/var/lib/mysql
        - ./mariadb-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  nginx:
    build:
      context: ./containers/nginx
      args:
          - PHP_UPSTREAM=php-fpm
    volumes:
        - ./data/logs/nginx/:/var/log/nginx
        - ./code:/var/www/html
  php:
    build:
      context: ./containers/php-fpm-alpine
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_COMPOSER=true
        - INSTALL_DRUPAL_CLI=true
        - HOST_IP=${HOST_IP}
    depends_on:
      - mariadb
    volumes:
      - ./data/logs/php/:/var/log
      - ./code:/var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    environment:
      mariadb_USERNAME: ${MARIADB_USERNAME}
      mariadb_ROOT_PASSWORD: ${MARIADB_PASSWORD}
#  solr:
#    build: ./containers/solr-3.x
#    ports:
#      - ${SOLR_HOST_PORT}:8983
#  grunt:
#    build: ./containers/grunt-alpine
#    volumes_from:
#      - applications
#    depends_on:
#      - applications
#  redis:
#    image: redis:alpine
#    volumes:
#      - ./data/redis:/data
#    ports:
#      - "${REDIS_HOST_PORT}:6379"
  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
##### DEVELOPMENT CONTAINERS
  utility-container:
    build:
      context: ./containers/utility-container
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_DRUSH=true
        - COMPOSER_GLOBAL_INSTALL=true
        - INSTALL_WORKSPACE_SSH=true
        - PUID=1000
        - PGID=1000
        - TZ=UTC
        - DEFAULT_TEST_CONFIG=${DEFAULT_TEST_CONFIG}
    ports:
      - "22"
    tty: true
volumes:
  mysql:
