version: '2'
services:

### Applications Code Container #############################
  applications:
    image: tianon/true
    volumes:
#      - ${PROJECTS_PATH}/${DRUPAL_8}:/var/www/drupal
#      - ${PROJECTS_PATH}/${SYMFONY_2}:/var/www/symfony
      - codebase-rsync-sync:/var/www/hidglobal/hid:rw
volumes:
  codebase-rsync-sync:
    external: true