version: '2'
services:

## Applications Code Container #############################
  applications:
    image: tianon/true
    volumes:
      - ${APPLICATION}:/var/www/drupal
  mariadb:
    build:
      context: ./containers/mariadb
    volumes:
        - mysql:/var/lib/mysql
    ports:
      - ${MARIADB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
  nginx:
    build:
      context: ./containers/nginx
      args:
          - PHP_UPSTREAM=php-fpm
    ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
        - ./data/logs/nginx/:/var/log/nginx
    volumes_from:
        - php-fpm
    links:
        - php-fpm
  php-fpm:
    build:
      context: ./containers/php-fpm-alpine
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_COMPOSER=true
        - INSTALL_DRUPAL_CLI=true
        - HOST_IP=${HOST_IP}
    depends_on:
      - mariadb
    volumes:
      - ./data/logs/php/:/var/log
    links:
      - mariadb
    ports:
      - "9000"
    volumes_from:
      - applications
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - ${PMA_PORT}:80
    environment:
      mariadb_USERNAME: ${MARIADB_USERNAME}
      mariadb_ROOT_PASSWORD: ${MARIADB_PASSWORD}
  solr3:
    build: ./containers/solr-3.x
    ports:
      - ${SOLR_HOST_PORT}:8983
  grunt:
    build: ./containers/grunt-alpine
    volumes_from:
      - applications
    depends_on:
      - applications
  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    ports:
      - "${REDIS_HOST_PORT}:6379"
volumes:
  mysql:
