version: '2'
services:

## Applications Code Container #############################
  applications:
    image: tianon/true
    extends:
      file: data/config/docker-compose-volumes.yml
      service: volumes-only
  mariadb:
    build:
      context: ./lib/services/mariadb
    volumes:
        - mysql:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
  nginx:
    build:
      context: ./lib/services/nginx
      args:
          - PHP_UPSTREAM=php-fpm
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./data/logs/nginx/:/var/log/nginx
        - ./data/config/sites:/etc/nginx/sites-available
    volumes_from:
        - php-fpm
    links:
        - php-fpm
  php-fpm:
    build:
      context: ./lib/services/php-fpm-alpine
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_COMPOSER=true
        - INSTALL_DRUPAL_CLI=true
        - HOST_IP=${HOST_IP}
    depends_on:
      - mariadb
    volumes:
      - ./data/logs/php/:/var/log
    links:
      - mariadb
    ports:
      - "9000"
    restart: always
    volumes_from:
      - applications
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - 8181:80
    environment:
      mariadb_USERNAME: root
      mariadb_ROOT_PASSWORD: secret
  solr3:
    build: ./lib/services/solr-3.x
    ports:
      - 8983:8983
    restart: always
  grunt:
    build: ./lib/services/grunt-alpine
    volumes_from:
      - applications
    depends_on:
      - applications
  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
  utility:
    build: ./lib/services/utility
    volumes:
      - ./data/config/utility:/utility
      - ~/.ssh/id_ed25519.pub:/root/.ssh/authorized_keys
    volumes_from:
      - applications
    depends_on:
      - applications
      - mariadb
    links:
      - mariadb:db
    environment:
      mariadb_USERNAME: root
      mariadb_ROOT_PASSWORD: secret
    ports:
      - "2222:22"
volumes:
  mysql:
